### PR TITLE
Add support for silverstripe 5

### PR DESCRIPTION
**Pull request by satrun77**
Update composer to support silverstripe 5. Tested with CMS 5 beta-1

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Part of me wonders given the APIs are so similar if this should be something like, we could tighten it down later if the APIs diverge to the point that it causes issues.
- silverstripe/framework ^4 | ^5
- silverstripe/vendor-plugin ^1.0 | ^2.0
- silverstripe/spamprotection ^3 | ^4

**Comment by UndefinedOffset** [comment]
Have a look at https://github.com/webbuilders-group/silverstripe-turnstile/blob/master/composer.json, also I'm pretty sure we can drop `silverstripe/vendor-plugin` now it's part of the core's dependencies so it's not needed even in 4.x.

**Comment by satrun77** [comment]
@UndefinedOffset PR updated

**Comment by UndefinedOffset** [comment]
Thanks :)

**Pull request merged**
