### PR TITLE
Compatibility with latest version of spam protection module

### PR DESCRIPTION
**Pull request by jonom**
1.2.* is not currently a valid option

Thanks for this module! Working great so far.

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Looks like it is to me there is a 1.2.0 tag https://github.com/silverstripe/silverstripe-spamprotection/releases

**Comment by jonom** [comment]
You're right. Problem is that my composer file is set to use the dev-master branch of spam protection. Composer is saying: _undefinedoffset/silverstripe-nocaptcha dev-master requires silverstripe/spamprotection 1.2.\* -> no matching package found._

I wonder if it's possible to set the minimum requirement to 1.2.\* *or* dev-master?

**Comment by UndefinedOffset** [comment]
Not that I'm aware of, I believe the spam protection module could set the master branch to be an alias of 1.2.x but form my end not really. The only thing I could do I think is put a * as the required version but that would also mean that not compatible versions would be an issue. My recommendation is to change the composer requirement in your project's composer.json to be 1.2.* or remove it. If you remove it, it will default to the version required by the other modules that require it.

**Comment by UndefinedOffset** [comment]
I don't believe this is an issue any more can you confirm? If it's not lets close this. I see a release for 1.2.* has been created.

**Comment by jonom** [comment]
Yeah everything works fine as long as you're happy using Spam Protection 1.2.x. If you've manually defined the dev-master or 2.x branch of SpamProtection you can't use this module as Composer will say it's not compatible. That might be true too, I haven't checked yet :)

Rather than closing I've changed the name of this issue to highlight the compatibility issue.

**Comment by jonom** [comment]
Oh this is a pull request, thought it was an issue :stuck_out_tongue: I'll close it for now

**Pull request closed without merging**
